/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as GamesRouteImport } from './routes/games'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadPackageNameRouteImport } from './routes/download.$packageName'
import { Route as AppPackageNameRouteImport } from './routes/app.$packageName'
import { Route as ApiPublicFetchDownloadRouteImport } from './routes/api/public/fetch-download'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadPackageNameRoute = DownloadPackageNameRouteImport.update({
  id: '/download/$packageName',
  path: '/download/$packageName',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPackageNameRoute = AppPackageNameRouteImport.update({
  id: '/app/$packageName',
  path: '/app/$packageName',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFetchDownloadRoute = ApiPublicFetchDownloadRouteImport.update({
  id: '/api/public/fetch-download',
  path: '/api/public/fetch-download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/games': typeof GamesRoute
  '/rankings': typeof RankingsRoute
  '/topics': typeof TopicsRoute
  '/trending': typeof TrendingRoute
  '/app/$packageName': typeof AppPackageNameRoute
  '/download/$packageName': typeof DownloadPackageNameRoute
  '/api/public/fetch-download': typeof ApiPublicFetchDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/games': typeof GamesRoute
  '/rankings': typeof RankingsRoute
  '/topics': typeof TopicsRoute
  '/trending': typeof TrendingRoute
  '/app/$packageName': typeof AppPackageNameRoute
  '/download/$packageName': typeof DownloadPackageNameRoute
  '/api/public/fetch-download': typeof ApiPublicFetchDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/games': typeof GamesRoute
  '/rankings': typeof RankingsRoute
  '/topics': typeof TopicsRoute
  '/trending': typeof TrendingRoute
  '/app/$packageName': typeof AppPackageNameRoute
  '/download/$packageName': typeof DownloadPackageNameRoute
  '/api/public/fetch-download': typeof ApiPublicFetchDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/auth'
    | '/games'
    | '/rankings'
    | '/topics'
    | '/trending'
    | '/app/$packageName'
    | '/download/$packageName'
    | '/api/public/fetch-download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/auth'
    | '/games'
    | '/rankings'
    | '/topics'
    | '/trending'
    | '/app/$packageName'
    | '/download/$packageName'
    | '/api/public/fetch-download'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/auth'
    | '/games'
    | '/rankings'
    | '/topics'
    | '/trending'
    | '/app/$packageName'
    | '/download/$packageName'
    | '/api/public/fetch-download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  AuthRoute: typeof AuthRoute
  GamesRoute: typeof GamesRoute
  RankingsRoute: typeof RankingsRoute
  TopicsRoute: typeof TopicsRoute
  TrendingRoute: typeof TrendingRoute
  AppPackageNameRoute: typeof AppPackageNameRoute
  DownloadPackageNameRoute: typeof DownloadPackageNameRoute
  ApiPublicFetchDownloadRoute: typeof ApiPublicFetchDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$packageName': {
      id: '/download/$packageName'
      path: '/download/$packageName'
      fullPath: '/download/$packageName'
      preLoaderRoute: typeof DownloadPackageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$packageName': {
      id: '/app/$packageName'
      path: '/app/$packageName'
      fullPath: '/app/$packageName'
      preLoaderRoute: typeof AppPackageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fetch-download': {
      id: '/api/public/fetch-download'
      path: '/api/public/fetch-download'
      fullPath: '/api/public/fetch-download'
      preLoaderRoute: typeof ApiPublicFetchDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  AuthRoute: AuthRoute,
  GamesRoute: GamesRoute,
  RankingsRoute: RankingsRoute,
  TopicsRoute: TopicsRoute,
  TrendingRoute: TrendingRoute,
  AppPackageNameRoute: AppPackageNameRoute,
  DownloadPackageNameRoute: DownloadPackageNameRoute,
  ApiPublicFetchDownloadRoute: ApiPublicFetchDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
