/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadPackageNameRouteImport } from './routes/download.$packageName'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AppPackageNameRouteImport } from './routes/app.$packageName'
import { Route as ApiPublicFetchDownloadRouteImport } from './routes/api/public/fetch-download'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadPackageNameRoute = DownloadPackageNameRouteImport.update({
  id: '/download/$packageName',
  path: '/download/$packageName',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const AppPackageNameRoute = AppPackageNameRouteImport.update({
  id: '/app/$packageName',
  path: '/app/$packageName',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFetchDownloadRoute = ApiPublicFetchDownloadRouteImport.update({
  id: '/api/public/fetch-download',
  path: '/api/public/fetch-download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/games': typeof GamesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rankings': typeof RankingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/topics': typeof TopicsRoute
  '/trending': typeof TrendingRoute
  '/app/$packageName': typeof AppPackageNameRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/download/$packageName': typeof DownloadPackageNameRoute
  '/api/public/fetch-download': typeof ApiPublicFetchDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/games': typeof GamesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rankings': typeof RankingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/topics': typeof TopicsRoute
  '/trending': typeof TrendingRoute
  '/app/$packageName': typeof AppPackageNameRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/download/$packageName': typeof DownloadPackageNameRoute
  '/api/public/fetch-download': typeof ApiPublicFetchDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/games': typeof GamesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rankings': typeof RankingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/topics': typeof TopicsRoute
  '/trending': typeof TrendingRoute
  '/app/$packageName': typeof AppPackageNameRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/download/$packageName': typeof DownloadPackageNameRoute
  '/api/public/fetch-download': typeof ApiPublicFetchDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apps'
    | '/articles'
    | '/auth'
    | '/contact'
    | '/dmca'
    | '/games'
    | '/privacy-policy'
    | '/rankings'
    | '/sitemap.xml'
    | '/terms'
    | '/topics'
    | '/trending'
    | '/app/$packageName'
    | '/articles/$slug'
    | '/download/$packageName'
    | '/api/public/fetch-download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apps'
    | '/articles'
    | '/auth'
    | '/contact'
    | '/dmca'
    | '/games'
    | '/privacy-policy'
    | '/rankings'
    | '/sitemap.xml'
    | '/terms'
    | '/topics'
    | '/trending'
    | '/app/$packageName'
    | '/articles/$slug'
    | '/download/$packageName'
    | '/api/public/fetch-download'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apps'
    | '/articles'
    | '/auth'
    | '/contact'
    | '/dmca'
    | '/games'
    | '/privacy-policy'
    | '/rankings'
    | '/sitemap.xml'
    | '/terms'
    | '/topics'
    | '/trending'
    | '/app/$packageName'
    | '/articles/$slug'
    | '/download/$packageName'
    | '/api/public/fetch-download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppsRoute: typeof AppsRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DmcaRoute: typeof DmcaRoute
  GamesRoute: typeof GamesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RankingsRoute: typeof RankingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TopicsRoute: typeof TopicsRoute
  TrendingRoute: typeof TrendingRoute
  AppPackageNameRoute: typeof AppPackageNameRoute
  DownloadPackageNameRoute: typeof DownloadPackageNameRoute
  ApiPublicFetchDownloadRoute: typeof ApiPublicFetchDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$packageName': {
      id: '/download/$packageName'
      path: '/download/$packageName'
      fullPath: '/download/$packageName'
      preLoaderRoute: typeof DownloadPackageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/app/$packageName': {
      id: '/app/$packageName'
      path: '/app/$packageName'
      fullPath: '/app/$packageName'
      preLoaderRoute: typeof AppPackageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fetch-download': {
      id: '/api/public/fetch-download'
      path: '/api/public/fetch-download'
      fullPath: '/api/public/fetch-download'
      preLoaderRoute: typeof ApiPublicFetchDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppsRoute: AppsRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DmcaRoute: DmcaRoute,
  GamesRoute: GamesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RankingsRoute: RankingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TopicsRoute: TopicsRoute,
  TrendingRoute: TrendingRoute,
  AppPackageNameRoute: AppPackageNameRoute,
  DownloadPackageNameRoute: DownloadPackageNameRoute,
  ApiPublicFetchDownloadRoute: ApiPublicFetchDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
